import Head from 'next/head'
import { Header, About, Banner , Clients, CTA, Display, Footer, Projects, Services } from '@/sections'


export default function Home() {
  return (
    <>
      <Head>
        <title>Olsson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner/>
        <Header/>
        <Clients/>
        <Services/>
        <Display/>
        <Projects/>
        <About/>
        <CTA/>
        <Footer/>
      </main>
    </>
  )
}
